### PR TITLE
Add global.json file.

### PR DESCRIPTION
**Pull request by tonysneed**
Add global.json file.

### CODE REVIEW

**Comment by tonysneed** [comment]
@lelong37 This is in progress ... Hold off on merging for now.

**Comment by lelong37** [comment]
Hey @tonysneed !

**Comment by tonysneed** [comment]
Hey @lelong37 It's OK, I'll create another PR to update the packages, and to fix the CI.

**Comment by lelong37** [comment]
Sounds, good standing by, over and out.

**Pull request merged**
