### PR TITLE
IQuery Should Have ThenInclude

### PR DESCRIPTION
**Pull request by tonysneed**
Added failing test: Fluent_Api_Should_Support_Nested_Includes.

### CODE REVIEW

**Comment by tonysneed** [comment]
@ydlkrishna Just about to complete the PR for adding a method for nested updates.
Turns out the `.ThenInclude` method is difficult to implement without changing from an interface (`IQuery`) to extension methods, due to generic covariance constraints.  So I plan to add a method that will accept a string for the navigation property path, matching the same method in the EF API.

**Comment by tonysneed** [comment]
Resolves #26 .

**Comment by tonysneed** [comment]
Yes, in the RTM release, which will be coming shortly.

**Comment by youngaj** [comment]
Thanks for this fix @tonysneed. I just ran into the problem using the v.1.10 nuget release.  Is there going to be a new nuget release to include this fix.

If not how do I target the current code base in place of the nuget package?  Would I need to copy the code locally to do so?

thanks in advance

**Pull request merged**
